apiVersion: v1
kind: Service
metadata:
  name: json-server
  labels:
    app: json-server
    app.kubernetes.io/managed-by: kustomize
spec:
  type: NodePort
  selector:
    app: json-server  # Solo este label - NO incluye version
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
