#canary-deployment/production/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: json-server
  labels:
    app: json-server
spec:
  type: NodePort
  selector:
    app: json-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
