apiVersion: v1
kind: Pod
metadata:
  name: mw-web
  labels:
    app.kubernetes.io/name: mw-web
    app.kubernetes.io/managed-by: manual
spec:
  containers:
  - name: nginx
    image: nginx:1.19
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: init
    image: ruby:2.7
    command: ["/bin/sh", "-c"]
    args:
    - >
      git clone https://github.com/Mikroways/mikroways.net.git &&
      cd mikroways.net &&
      bundle install &&
      jekyll build &&
      mv _site/* /html
    volumeMounts:
    - name: html
      mountPath: /html
  volumes:
  - name: html
    emptyDir: {}
