apiVersion: v1
kind: Pod
metadata:
  name: mysql-with-probes
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "200m"
    ports:
    - containerPort: 3306
    livenessProbe:
      exec:
        command:
        - mysqladmin
        - ping
        - -h
        - localhost
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      exec:
        command:
        - mysql
        - -h
        - localhost
        - -u
        - root
        - -proot
        - -e
        - "SELECT 1"
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 3
