apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    release: demo
    version: "1.19"
spec:
  containers:
  - name: nginx
    image: nginx:1.19
    ports:
    - containerPort: 80
