apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actividad-03

resources:
- ../../base

namePrefix: stable-
nameSuffix: "-v1"

replicas:
- name: json-server
  count: 3

configMapGenerator:
- name: json-server-db
  files:
  - db.json

commonLabels:
  version: stable
  release: production

# Asegurar que los pods tienen label version: stable
patches:
- target:
    kind: Deployment
    name: json-server
  patch: |-
    - op: add
      path: /spec/selector/matchLabels/version
      value: stable
    - op: add
      path: /spec/template/metadata/labels/version
      value: stable
