#canary-deployment/overlays/stable/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actividad-03

resources:
- ../../base

namePrefix: stable-
nameSuffix: -v1

replicas:
- count: 3
  name: json-server

configMapGenerator:
- files:
  - db.json
  name: json-server-db


# Asegurar que los pods tienen label version: stable
patches:
- patch: |-
    - op: add
      path: /spec/selector/matchLabels/version
      value: stable
    - op: add
      path: /spec/template/metadata/labels/version
      value: stable
  target:
    kind: Deployment
    name: json-server
labels:
- includeSelectors: true
  pairs:
    release: production
    version: stable
