apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actividad-03

resources:
- ../../base

namePrefix: canary-
nameSuffix: "-v2"

replicas:
- name: json-server
  count: 1

configMapGenerator:
- name: json-server-db
  files:
  - db.json

commonLabels:
  version: canary
  release: testing

# Asegurar que los pods tienen label version: canary
patches:
- target:
    kind: Deployment
    name: json-server
  patch: |-
    - op: add
      path: /spec/selector/matchLabels/version
      value: canary
    - op: add
      path: /spec/template/metadata/labels/version
      value: canary
