#canary-deployment/overlays/canary/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actividad-03

resources:
- ../../base

namePrefix: canary-
nameSuffix: -v2

replicas:
- count: 1
  name: json-server

configMapGenerator:
- files:
  - db.json
  name: json-server-db


# Asegurar que los pods tienen label version: canary
patches:
- patch: |-
    - op: add
      path: /spec/selector/matchLabels/version
      value: canary
    - op: add
      path: /spec/template/metadata/labels/version
      value: canary
  target:
    kind: Deployment
    name: json-server
labels:
- includeSelectors: true
  pairs:
    release: testing
    version: canary
