apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mikroways-local-claim
  namespace: actividad-04
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mikroways-local