apiVersion: v1
kind: Service
metadata:
  name: my-dns
  namespace: actividad-04
spec:
  # Nota: NO hay "selector" - endpoints serán manuales
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
---  #  Separador obligatorio
apiVersion: v1  #  apiVersion obligatorio
kind: Endpoints
metadata:
  name: my-dns  #  DEBE coincidir exactamente con el nombre del servicio
  namespace: actividad-04
subsets:
- addresses:
  - ip: 8.8.8.8  # Google DNS público
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP