apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-hostpath
  namespace: actividad-04
  labels:
    app: mysql-hostpath
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mysql-hostpath
  template:
    metadata:
      labels:
        app: mysql-hostpath
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "testdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:
      - name: mysql-storage
        hostPath:
          path: /var/lib/mysql-k8s-hostpath
          type: DirectoryOrCreate