apiVersion: v1
kind: Pod
metadata:
  name: secret-mount-test
  labels:
    app: secret-test
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]  # Mantener el pod corriendo
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-generic-secret
      defaultMode: 0400  # Permisos 0400 por defecto
      items:
      - key: user
        path: username.txt
        mode: 0400
      - key: password
        path: password.txt
        mode: 0400
